### ISSUE TITLE
exception for bin/Combocheck.jar

### ISSUE THREAD

**Issue by zhaofeng-shu33** [Goldensunboy/combocheck#1]
Hi, I use your software but finds some difficulty. It throws exception when I click `compare` button.
```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringEscapeUtils
        at com.combocheck.ui.ComparisonDialog.<init>(ComparisonDialog.java:125)
        at com.combocheck.ui.report.ReportEntry$ReportMouseListener.mousePressed(ReportEntry.java:87)
        at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6400)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
I could not figure out what's wrong.

**Comment by Goldensunboy** [comment]
I could not reproduce this. Perhaps you are using an older version of the Apache Commons library?

Try downloading version 3 or later, and run Combocheck with `java -cp .;commons-lang3-3.1-sources.jar ComboCheck` (with the name of the jar file you downloaded for Apache Commons)

**Comment by zhaofeng-shu33** [comment]
> I could not reproduce this. Perhaps you are using an older version of the Apache Commons library?
> 
> Try downloading version 3 or later, and run Combocheck with `java -cp .;commons-lang3-3.1-sources.jar ComboCheck` (with the name of the jar file you downloaded for Apache Commons)

I use 3.8-2 and my operating system is debian 10.

**Comment by zhaofeng-shu33** [comment]
By the way, how to rebuild the jar from source?

**Comment by Goldensunboy** [comment]
I have not touched this project in 5 years and just looking at it now, it seems there are still some bugs I must have missed back then (#2).

I do plan to try fixing the bugs, though. If you are okay with a few bugs for now and wish to try this comparison tool - I have just now committed the dependent JARs, and it should be possible to try building a fat JAR in Eclipse for this. I have not set up maven/gradle because I'm not good at it.

**Comment by Goldensunboy** [comment]
I have also committed the new binary which is a fat JAR containing the dependency you were missing. Try it now.

**Comment by zhaofeng-shu33** [comment]
Thanks for your new commit. I will give it a try.
